/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunRuang;

/**
 *
 * @author Asus
 */
public class balokDiagonal extends javax.swing.JPanel {

    /**
     * Creates new form balokDiagonal
     */
    public balokDiagonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 64, 105));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel2.setText("Dikarenakan panjang semua sisi belah ketupat sama, sehingga rumus kelilingnya ialah :");
        add(jLabel2);
        jLabel2.setBounds(20, 20, 1030, 30);

        jLabel1.setFont(new java.awt.Font("Flame Fetish", 1, 48)); // NOI18N
        jLabel1.setText("Rumus : 4 x sisi");
        add(jLabel1);
        jLabel1.setBounds(60, 160, 341, 70);

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel3.setText("Contoh Soal:");
        add(jLabel3);
        jLabel3.setBounds(20, 110, 190, 40);

        jLabel4.setFont(new java.awt.Font("Flame Fetish", 1, 48)); // NOI18N
        jLabel4.setText("Diagonal Ruang : k  ");
        add(jLabel4);
        jLabel4.setBounds(20, 50, 670, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
