/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunRuang;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.app.pbo.TampilanUtama;
import ui.app.pbo.bangunRuangClass;

/**
 *
 * @author SONY
 */
public class bolaa extends javax.swing.JFrame {

    /**
     * Creates new form bolaa
     */
    bolaDiameter bDiamet;
    bolaDiameterGambar gbr1;
    bolaLuasPermukaan bLuas;
    bolaLuasPermukaanGambar gbr2;
    bolaVolume bVolume;
    bolaVolumeGambar gbr3;
    bolaLatihanSoal1 bLatsol1;
    bolaLatihanSoal2 bLatsol2;
    bolaLatihanSoal3 bLatsol3;
    bolaLatihanSoal4 bLatsol4;
    bolaLatihanSoal5 bLatsol5;
    bolaLatihanSoal6 bLatsol6;
    
    public bolaa() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        bDiamet = new bolaDiameter();
        bLuas = new bolaLuasPermukaan();
        bVolume = new bolaVolume();
        bLatsol1 = new bolaLatihanSoal1();
        bLatsol2 = new bolaLatihanSoal2();
        bLatsol3 = new bolaLatihanSoal3();
        bLatsol4 = new bolaLatihanSoal4();
        bLatsol5 = new bolaLatihanSoal5();
        bLatsol6 = new bolaLatihanSoal6();
        gbr1 = new bolaDiameterGambar();
        gbr2 = new bolaLuasPermukaanGambar();
        gbr3 = new bolaVolumeGambar();
        
        panelGambar.add(gbr1);
        panelGambar.add(gbr2);
        panelGambar.add(gbr3);
        panelUtama.add(bDiamet);
        panelUtama.add(bLuas);
        panelUtama.add(bVolume);
        panelUtama.add(bLatsol1);
        panelUtama.add(bLatsol2);
        panelUtama.add(bLatsol3);
        panelUtama.add(bLatsol4);
        panelUtama.add(bLatsol5);
        panelUtama.add(bLatsol6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGambar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ButtonLatSoal1 = new javax.swing.JLabel();
        ButtonLatSoal2 = new javax.swing.JLabel();
        ButtonLatSoal3 = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        ButtonLatSoal4 = new javax.swing.JLabel();
        ButtonLatSoal5 = new javax.swing.JLabel();
        ButtonLatSoal6 = new javax.swing.JLabel();
        diameterJari = new javax.swing.JLabel();
        lsPermukaan = new javax.swing.JLabel();
        volumeBola = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1304, 816));
        setUndecorated(true);
        getContentPane().setLayout(null);

        panelGambar.setBackground(new java.awt.Color(8, 80, 116));
        panelGambar.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelGambar);
        panelGambar.setBounds(300, 60, 570, 380);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(820, 60, 470, 170);

        ButtonLatSoal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal (7).png"))); // NOI18N
        ButtonLatSoal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLatSoal1MouseClicked(evt);
            }
        });
        getContentPane().add(ButtonLatSoal1);
        ButtonLatSoal1.setBounds(880, 220, 130, 120);

        ButtonLatSoal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal (8).png"))); // NOI18N
        ButtonLatSoal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLatSoal2MouseClicked(evt);
            }
        });
        getContentPane().add(ButtonLatSoal2);
        ButtonLatSoal2.setBounds(1020, 220, 130, 120);

        ButtonLatSoal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal (9).png"))); // NOI18N
        ButtonLatSoal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLatSoal3MouseClicked(evt);
            }
        });
        getContentPane().add(ButtonLatSoal3);
        ButtonLatSoal3.setBounds(1160, 220, 130, 120);

        panelUtama.setBackground(new java.awt.Color(24, 64, 105));
        panelUtama.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelUtama);
        panelUtama.setBounds(300, 450, 990, 340);

        ButtonLatSoal4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal (10).png"))); // NOI18N
        ButtonLatSoal4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLatSoal4MouseClicked(evt);
            }
        });
        getContentPane().add(ButtonLatSoal4);
        ButtonLatSoal4.setBounds(880, 350, 130, 110);

        ButtonLatSoal5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal (11).png"))); // NOI18N
        ButtonLatSoal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLatSoal5MouseClicked(evt);
            }
        });
        getContentPane().add(ButtonLatSoal5);
        ButtonLatSoal5.setBounds(1020, 350, 130, 110);

        ButtonLatSoal6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/soal/latihan soal (12).png"))); // NOI18N
        ButtonLatSoal6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLatSoal6MouseClicked(evt);
            }
        });
        getContentPane().add(ButtonLatSoal6);
        ButtonLatSoal6.setBounds(1160, 350, 130, 110);

        diameterJari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Bola/diameter jr bola.png"))); // NOI18N
        diameterJari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diameterJariMouseClicked(evt);
            }
        });
        getContentPane().add(diameterJari);
        diameterJari.setBounds(30, 60, 250, 240);

        lsPermukaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Bola/luas perm bola .png"))); // NOI18N
        lsPermukaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsPermukaanMouseClicked(evt);
            }
        });
        getContentPane().add(lsPermukaan);
        lsPermukaan.setBounds(30, 310, 250, 240);

        volumeBola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Bola/volume bola.png"))); // NOI18N
        volumeBola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumeBolaMouseClicked(evt);
            }
        });
        getContentPane().add(volumeBola);
        volumeBola.setBounds(30, 560, 250, 230);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("O");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home icon kecil.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1171, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1310, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bgkecil.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1310, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void ButtonLatSoal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLatSoal1MouseClicked
        gbr1.setVisible(false);
        bDiamet.setVisible(false);
        gbr2.setVisible(true);
        bLuas.setVisible(false);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(true);
        bLatsol2.setVisible(false);
        bLatsol3.setVisible(false);
        bLatsol4.setVisible(false);
        bLatsol5.setVisible(false);
        bLatsol6.setVisible(false);
    }//GEN-LAST:event_ButtonLatSoal1MouseClicked

    private void ButtonLatSoal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLatSoal2MouseClicked
        gbr1.setVisible(false);
        bDiamet.setVisible(false);
        gbr2.setVisible(false);
        bLuas.setVisible(false);
        gbr3.setVisible(true);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(true);
        bLatsol3.setVisible(false);
        bLatsol4.setVisible(false);
        bLatsol5.setVisible(false);
        bLatsol6.setVisible(false);
    }//GEN-LAST:event_ButtonLatSoal2MouseClicked

    private void ButtonLatSoal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLatSoal3MouseClicked
        //luas
        gbr1.setVisible(false);
        bDiamet.setVisible(false);
        gbr2.setVisible(true);
        bLuas.setVisible(false);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(false);
        bLatsol3.setVisible(true);
        bLatsol4.setVisible(false);
        bLatsol5.setVisible(false);
        bLatsol6.setVisible(false);
    }//GEN-LAST:event_ButtonLatSoal3MouseClicked

    private void ButtonLatSoal4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLatSoal4MouseClicked
        //diameter
        gbr1.setVisible(true);
        bDiamet.setVisible(false);
        gbr2.setVisible(false);
        bLuas.setVisible(false);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(false);
        bLatsol3.setVisible(false);
        bLatsol4.setVisible(true);
        bLatsol5.setVisible(false);
        bLatsol6.setVisible(false);
    }//GEN-LAST:event_ButtonLatSoal4MouseClicked

    private void ButtonLatSoal5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLatSoal5MouseClicked
        //jari
        gbr1.setVisible(true);
        bDiamet.setVisible(false);
        gbr2.setVisible(false);
        bLuas.setVisible(false);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(false);
        bLatsol3.setVisible(false);
        bLatsol4.setVisible(false);
        bLatsol5.setVisible(true);
        bLatsol6.setVisible(false);
    }//GEN-LAST:event_ButtonLatSoal5MouseClicked

    private void ButtonLatSoal6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLatSoal6MouseClicked
        //volLuas
        gbr1.setVisible(false);
        bDiamet.setVisible(false);
        gbr2.setVisible(true);
        bLuas.setVisible(false);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(false);
        bLatsol3.setVisible(false);
        bLatsol4.setVisible(false);
        bLatsol5.setVisible(false);
        bLatsol6.setVisible(true);
    }//GEN-LAST:event_ButtonLatSoal6MouseClicked

    private void diameterJariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diameterJariMouseClicked
        // TODO add your handling code here:
        gbr1.setVisible(true);
        bDiamet.setVisible(true);
        gbr2.setVisible(false);
        bLuas.setVisible(false);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(false);
    }//GEN-LAST:event_diameterJariMouseClicked

    private void lsPermukaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsPermukaanMouseClicked
        // TODO add your handling code here:
        gbr1.setVisible(false);
        bDiamet.setVisible(false);
        gbr2.setVisible(true);
        bLuas.setVisible(true);
        gbr3.setVisible(false);
        bVolume.setVisible(false);
        bLatsol1.setVisible(false);
        bLatsol2.setVisible(false);
    }//GEN-LAST:event_lsPermukaanMouseClicked

    private void volumeBolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumeBolaMouseClicked
        // TODO add your handling code here:
        gbr1.setVisible(false);
        bDiamet.setVisible(false);
        gbr2.setVisible(false);
        bLuas.setVisible(false);
        gbr3.setVisible(true);
        bVolume.setVisible(true);
    }//GEN-LAST:event_volumeBolaMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int pilih = JOptionPane.showConfirmDialog(null, "Selesai Belajar?", "AMOBA", JOptionPane.YES_NO_OPTION);

        if(pilih == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        bangunRuangClass menuRuang = new bangunRuangClass();
        new bangunRuangClass().setVisible(true);
        menuRuang.pack();
        menuRuang.setLocationRelativeTo(null);
        menuRuang.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        TampilanUtama utama = new TampilanUtama();
        new TampilanUtama().setVisible(true);
        utama.pack();
        utama.setLocationRelativeTo(null);
        utama.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bolaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bolaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bolaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bolaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bolaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonLatSoal1;
    private javax.swing.JLabel ButtonLatSoal2;
    private javax.swing.JLabel ButtonLatSoal3;
    private javax.swing.JLabel ButtonLatSoal4;
    private javax.swing.JLabel ButtonLatSoal5;
    private javax.swing.JLabel ButtonLatSoal6;
    private javax.swing.JLabel diameterJari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lsPermukaan;
    private javax.swing.JPanel panelGambar;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel volumeBola;
    // End of variables declaration//GEN-END:variables
}
