/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunRuang;

/**
 *
 * @author Asus
 */
public class limasLatihanSoal3 extends javax.swing.JPanel {

    /**
     * Creates new form limasLatihanSoal3
     */
    public limasLatihanSoal3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Diketahui limas ABCD dengan tinggi T");
        add(jLabel5);
        jLabel5.setBounds(20, 80, 500, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tentukan luas permukaan prisma tersebut!");
        add(jLabel4);
        jLabel4.setBounds(20, 160, 500, 32);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jawabanmu : ");
        add(jLabel8);
        jLabel8.setBounds(50, 210, 140, 24);

        jButton1.setText("Cek");
        add(jButton1);
        jButton1.setBounds(90, 250, 52, 32);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(190, 200, 170, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(190, 250, 170, 40);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("6 cm");
        add(jLabel6);
        jLabel6.setBounds(860, 260, 41, 16);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("panjang TZ = 15 cm, BC = 6 cm");
        add(jLabel7);
        jLabel7.setBounds(20, 120, 500, 32);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Z");
        add(jLabel9);
        jLabel9.setBounds(850, 240, 41, 16);

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("15 cm");
        add(jLabel10);
        jLabel10.setBounds(830, 180, 41, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Limas/gambar soal lim4.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(620, 0, 360, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Limas/soal.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
