/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunRuang;

/**
 *
 * @author Asus
 */
public class limasLuasPermukaanGambar extends javax.swing.JPanel {

    /**
     * Creates new form limasLuasPermukaanGambar
     */
    public limasLuasPermukaanGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 80, 116));
        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Limas/jaring-jaring-limas.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(550, 120, 270, 230);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Limas/jaring jaring lim5.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(220, 110, 270, 230);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Limas/luaspergam.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(-100, 0, 870, 800);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
