/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunRuang;

/**
 *
 * @author Asus
 */
public class prismaLuasPermukaanGambar extends javax.swing.JPanel {

    /**
     * Creates new form prismaLuasPermukaanGambar
     */
    public prismaLuasPermukaanGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 80, 116));
        setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Prisma/gambar-jaring-jaring-limas-segilima-model-2.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(70, 20, 300, 270);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prisma Segi Lima");
        add(jLabel5);
        jLabel5.setBounds(100, 310, 180, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Prisma/jaring-jaring-prisma-segitiga-ii.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(360, 20, 300, 300);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prisma Segi Tiga");
        add(jLabel6);
        jLabel6.setBounds(420, 320, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Prisma/Jaring-Jaring-Prisma-Segi-Enam.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(670, 20, 300, 280);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prisma Segi Enam");
        add(jLabel2);
        jLabel2.setBounds(730, 320, 180, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
