/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunDatar;

/**
 *
 * @author Asus
 */
public class belahKetupatKeliling extends javax.swing.JPanel {

    /**
     * Creates new form belahKetupatKeliling
     */
    public belahKetupatKeliling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 64, 105));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Flame Fetish", 1, 48)); // NOI18N
        jLabel1.setText("Rumus : 4 x sisi");
        add(jLabel1);
        jLabel1.setBounds(320, 70, 366, 70);

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        jLabel2.setText("Dikarenakan panjang semua sisi belah ketupat sama, sehingga rumus kelilingnya ialah :");
        add(jLabel2);
        jLabel2.setBounds(20, 20, 1030, 30);

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel3.setText("Contoh Soal:");
        add(jLabel3);
        jLabel3.setBounds(20, 110, 190, 40);

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel4.setText("maka berapa panjang masing masing sisi belah ketupat tesebut? ");
        add(jLabel4);
        jLabel4.setBounds(20, 160, 900, 70);

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        jLabel5.setText("Diketahui keliling sebuah belah ketupat ialah 32 cm,");
        add(jLabel5);
        jLabel5.setBounds(20, 130, 730, 70);

        jLabel6.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N
        jLabel6.setText("Jawab : ");
        add(jLabel6);
        jLabel6.setBounds(20, 210, 130, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("1.) Diketahui keliling : 32");
        add(jLabel7);
        jLabel7.setBounds(180, 240, 320, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("2.) Sehingga 32 = 4 x sisi");
        add(jLabel8);
        jLabel8.setBounds(180, 280, 310, 40);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("3.) maka, sisi = 32/4");
        add(jLabel9);
        jLabel9.setBounds(520, 238, 260, 32);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("4.) sisi = 8 cm");
        add(jLabel10);
        jLabel10.setBounds(520, 280, 210, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
