/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunDatar;

/**
 *
 * @author Asus
 */
public class persegiGambar extends javax.swing.JPanel {

    /**
     * Creates new form persegiGambar
     */
    public persegiGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonKeliling = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 80, 116));
        setLayout(null);

        jPanel1.setLayout(null);
        add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        buttonKeliling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/persegi/pergam.png"))); // NOI18N
        buttonKeliling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKelilingMouseClicked(evt);
            }
        });
        add(buttonKeliling);
        buttonKeliling.setBounds(20, 0, 530, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKelilingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKelilingMouseClicked

    }//GEN-LAST:event_buttonKelilingMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonKeliling;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
