/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunDatar;

import javax.swing.JOptionPane;

/**
 *
 * @author SONY
 */
public class psgPanjangLatsol1 extends javax.swing.JPanel {

    /**
     * Creates new form psgPanjangLatsol1
     */
    String jawaban;
    
    public psgPanjangLatsol1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        cekKunci = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(jTextField1);
        jTextField1.setBounds(200, 210, 150, 40);
        add(jTextField2);
        jTextField2.setBounds(200, 210, 150, 40);
        add(jTextField3);
        jTextField3.setBounds(590, 210, 200, 40);

        cekKunci.setText("CEK KUNCI");
        cekKunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekKunciActionPerformed(evt);
            }
        });
        add(cekKunci);
        cekKunci.setBounds(420, 210, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PsgPanjang/ls pers (1).png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void cekKunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekKunciActionPerformed
        // TODO add your handling code here:
        jawaban = jTextField1.getText();
        
        if(jawaban.equals("1350")){
            jTextField2.setText("Jawaban Benar : 1350 cm");
        } else {
            JOptionPane.showMessageDialog(this, "Jawabanmu belum tepat!");
        }
    }//GEN-LAST:event_cekKunciActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekKunci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
