/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bangunDatar;

/**
 *
 * @author SONY
 */
public class psgPanjangLatsol1 extends javax.swing.JPanel {

    /**
     * Creates new form psgPanjangLatsol1
     */
    public psgPanjangLatsol1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(jTextField1);
        jTextField1.setBounds(200, 210, 150, 40);
        add(jTextField2);
        jTextField2.setBounds(200, 210, 150, 40);
        add(jTextField3);
        jTextField3.setBounds(590, 210, 200, 40);

        jButton1.setText("CEK KUNCI");
        add(jButton1);
        jButton1.setBounds(430, 210, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ls pers (1).png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 340);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
